name: SyncToGitlab

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Github Sync to Gitlab
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITLAB_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:emCupid/adg_cn.git
          destination-repo: git@gitlab.com:emCupid/adg_cn.git